{% set name = "stackvana-final" %}
# LSST DM versions are prefixed with letters
#
#  - a weekly build is 'w_2018_50'
#  - a major release is 'v18_1'
#
# In order to play nice with conda, we take the following conventions
#
#  - for a weekly build 'w_2018_50', the conda version is '0.2018.50'
#  - for a major version 'v18_1', the conda version is '18.1.0'
#
{% set version = "0.2024.13" %}
{% set patch_version = version.split(".")[-1] if version.split(".")[-1].__len__() == 2 else "0" + version.split(".")[-1] %}
{% set dm_tag = "w_" + version.split(".")[1] + "_" + patch_version if version.startswith("0.") else "v" + version.replace(".", "_") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://eups.lsst.codes/stack/src/tags/{{ dm_tag }}.list
  sha256: 6d1cff0bb71e4a79f3d6d4a3c51e995842993349a345e3dd6733f91db103cf55

build:
  number: 0

outputs:
  - name: stackvana-{{ eups_product }}
    version: {{ version }}
    script: build_product.sh
    build:
      skip: true  # [win or py != 311]
      merge_build_host: true
    requirements:
      host:
        - stackvana-core =={{ version }}
        - stackvana-meas_algorithms =={{ version }}
        - python
      run:
        - python
        - stackvana-core =={{ version }}
        - stackvana-meas_algorithms =={{ version }}
    test:
      commands:
        - setup {{ eups_product }}
        - python -c "import lsst"
        - if [[ ! `eups list -s | grep "{{ eups_product }}"` ]]; then exit 1; fi

  - name: stackvana
    version: {{ version }}
    script: build_stackvana.sh
    build:
      skip: true  # [win or py != 311]
      merge_build_host: true
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("stackvana-" ~ eups_product, max_pin="x.x.x") }}
    test:
      commands:
        - python -c "import lsst"

about:
  home: https://github.com/beckermr/stackvana-core
  license: GPL-3.0-or-later
  license_family: GPL
  license_file:
    - LICENSE
    - COPYRIGHT
    - licenses/firefly-client.txt  # this one can be removed on the next version bump
    - licenses/scarlet.txt
    - licenses/eigen.txt  # this one can be removed when eigen 3.4 is pulled from conda-forge
    - licenses/kht.txt
  summary: stackvana build up to lsst_distrib

extra:
  recipe-maintainers:
    - beckermr
