# LSST DM versions are prefixed with letters
#
#  - a weekly build is 'w_2018_50'
#  - a major release is 'v18_1'
#
# In order to play nice with conda, we take the following conventions
#
#  - for a weekly build 'w_2018_50', the conda version is '0.2018.50'
#  - for a major version 'v18_1_0', the conda version is '18.1.0'
#
context:
  name: stackvana
  version: "0.2025.47"
  raw_major_version: '${{ (version | split("."))[0] }}'
  raw_minor_version: '${{ (version | split("."))[1] }}'
  raw_patch_version: '${{ (version | split("."))[2] }}'
  patch_version: ${{ "_" + raw_patch_version if (raw_patch_version | length) == 2 else "_0"  + raw_patch_version }}
  weekly_dm_tag: ${{ "w_" + raw_minor_version + patch_version }}
  non_weekly_dm_tag: ${{ "v" + (version | replace(".", "_")) }}
  dm_tag: ${{ weekly_dm_tag if raw_major_version == '0' else non_weekly_dm_tag }}

recipe:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://eups.lsst.codes/stack/src/tags/${{ dm_tag }}.list
  sha256: 26cc3b9b516c33bf174fdc97bd3bc7973ee0fd22cdc82c6a05980d165cad4309

build:
  number: 0
  skip:
    - win
    - match(python, "!=${{ lsst_pyver }}")
  merge_build_and_host_envs: true

outputs:
  - package:
      name: stackvana-${{ eups_product }}
    build:
      script: build_product.sh
    requirements:
      host:
        - stackvana-core ==${{ version }}
        - python
      run:
        - python
        - stackvana-core ==${{ version }}
    tests:
      - script:
          - setup ${{ eups_product }}
          - python -c "import lsst"
          - if [[ ! `eups list -s | grep "${{ eups_product }}"` ]]; then exit 1; fi

  - package:
      name: stackvana
    build:
      script: build_stackvana.sh
    requirements:
      host:
        - python
      run:
        - python
        - ${{ pin_subpackage("stackvana-" ~ eups_product, upper_bound="x.x.x") }}
    tests:
      - script:
          - python -c "import lsst"

about:
  homepage: https://github.com/beckermr/stackvana-core
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - COPYRIGHT
    - licenses/firefly-client.txt  # this one can be removed on the next version bump
    - licenses/scarlet.txt
    - licenses/eigen.txt  # this one can be removed when eigen 3.4 is pulled from conda-forge
    - licenses/kht.txt
  summary: stackvana build up to lsst_distrib

extra:
  recipe-maintainers:
    - beckermr
