conda_forge_output_validation: true
azure:
  free_disk_space:
    - apt
    - cache
    - docker
bot:
  automerge: true
  check_solvable: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
conda_build_tool: rattler-build
