conda_forge_output_validation: true
conda_build_tool: conda-build
conda_solver: libmamba
bot:
  automerge: true
  check_solvable: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
